org.gradle.jvmargs=-Xmx8G -Dorg.gradle.logging.level=warn -Djava.util.concurrent.ForkJoinPool.common.parallelism=1
org.gradle.daemon=false
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

## Mod Properties
mod_id=resourcedatapackloader
mod_name=Resource Data Pack Loader
mod_authors=tgstyle
mod_license=GPL-3.0
mod_description=Loads resource and data overrides from a global folder, applied across all worlds
mod_url=https://www.curseforge.com/minecraft/mc-mods/mct-resource-data-pack-loader
