modLoader="javafml"
loaderVersion="[${version_forge_min},)"
license="${mod_license}"

[[mods]]
modId="resourcedatapackloader"
version="${version}"
displayName="${mod_name}"
displayURL="${mod_url}"
authors="${mod_authors}"
description='''${mod_description}'''

[[dependencies.resourcedatapackloader]]
modId="forge"
mandatory=true
versionRange="[${version_forge_min},)"
ordering="NONE"
side="BOTH"

[[dependencies.resourcedatapackloader]]
modId="minecraft"
mandatory=true
versionRange="[${version_mc}]"
ordering="NONE"
side="BOTH"
