modLoader="javafml"
loaderVersion="[1,)"
license="${mod_license}"

[[mods]]
modId="resourcedatapackloader"
version="${version}"
displayName="${mod_name}"
displayURL="${mod_url}"
authors="${mod_authors}"
description='''${mod_description}'''

[[dependencies.resourcedatapackloader]]
modId="neoforge"
type="required"
versionRange="[${version_neoforge_min},)"
ordering="NONE"
side="BOTH"

[[dependencies.resourcedatapackloader]]
modId="minecraft"
type="required"
versionRange="[${version_mc}]"
ordering="NONE"
side="BOTH"

[[mixins]]
config="mixins.resourcedatapackloader.json"
