#Sat Sep 26 14:33:40 MDT 2026
build_number=437
devsync_bp=blastplaster-4.1.0-28e0e98-dirty-20260926112156
stage=release
version=4.0.0
version_betterf3=qX8kcwKf
version_bp=[4.1.0-b22-release,)
version_cloth=TimoYzse
version_curios=15.0.0+26.1.2
version_jei=29.43.0.105
version_mc=26.1.2
version_mc_label=26.1.2
version_mc_range=[26.1.2,26.2)
version_neoforge=26.1.2.109
version_neoforge_min=26.1.2
