#Sat Sep 26 14:33:55 MDT 2026
build_number=440
devsync_bp=blastplaster-4.1.0-28e0e98-dirty-20260926112156
stage=release
version=5.0.0
version_betterf3=GKmHNRiK
version_bp=[4.1.0-b22-release,)
version_cloth=zErG1kOw
version_curios=16.0.0+26.2
version_jei=30.38.0.230
version_mc=26.2
version_mc_label=26.2
version_mc_range=[26.2,26.3)
version_neoforge=26.2.0.88
version_neoforge_min=26.2
