#Mon Sep 28 09:57:19 MDT 2026
build_number=448
devsync_bp=blastplaster-4.1.0-ffa1ab6-dirty-20260927141831
stage=release
version=6.0.0
version_bp=[4.1.0-b22-release,)
version_cloth=GchRXPnb
version_curios=17.0.0-beta.2+26.3
version_jei=31.7.0.45
version_mc=26.3
version_mc_label=26.3
version_mc_range=[26.3,26.4)
version_neoforge=26.3.0.25-beta
version_neoforge_min=26.3
