#Wed Sep 30 10:31:54 MDT 2026
build_number=458
devsync_bp=blastplaster-4.1.0-9244384
stage=release
version=6.0.0
version_bp=[4.1.0-b22-release,)
version_cloth=GchRXPnb
version_jei=31.8.0.49
version_mc=26.3
version_mc_label=26.3
version_mc_range=[26.3,26.4)
version_neoforge=26.3.0.40-beta
version_neoforge_min=26.3
